GymBooker1/Controllers/GymClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GymBooker1.Controllers;
using GymBooker1.Models;

namespace GymBooker1.Views
{
    public class GymClassesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: GymCategories/Category/{category}
        public ActionResult Categories(string id) // id is actually the name of the category.
        {
            if (id == null)
            {
                return View("../Home/Index");
            }

            var gymClasses = new List<GymClass>();

            gymClasses = db.GymClasses
                    .Where(d => d.Category == id)
                    .OrderBy(d => d.Category)
                    .ThenBy(d => d.Name).ToList();

            ViewBag.category = id;

            ViewBag.pics = GetPics.GetCategoryPic(ViewBag.category);

            return View(gymClasses.ToList());
        }

        
        // GET: GymClasses/Show/5
        public ActionResult Show(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //GymClass gymClass = db.GymClasses.Find(id);
            var gymClass = db.GymClasses.SingleOrDefault(d => d.Name == id);
            if (gymClass == null)
            {
                return HttpNotFound();
            }

            ViewBag.pics = GetPics.Get2Pics(gymClass.Name);

            return View(gymClass);
        }




        ///////////////////// ADMIN ROUTES TO UPDATE GYM CLASSES. NOT LIKELY TO IMPLEMENT. ////////////////////
        // GENERATED CODE

        // GET: GymClasses
        [Authorize(Roles ="Admin2")]
        public ActionResult Index()
        {
            return View(db.GymClasses.ToList());
        }

        // GET: GymClasses/Details/5
        [Authorize(Roles = "Admin2")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GymClass gymClass = db.GymClasses.Find(id);
            if (gymClass == null)
            {
                return HttpNotFound();
            }
            return View(gymClass);
        }

        // GET: GymClasses/Create
        [Authorize(Roles = "Admin2")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: GymClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin2")]
        public ActionResult Create([Bind(Include = "Id,Name,Description")] GymClass gymClass)
        {
            if (ModelState.IsValid)
            {
                db.GymClasses.Add(gymClass);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gymClass);
        }

        // GET: GymClasses/Edit/5
        [Authorize(Roles = "Admin2")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GymClass gymClass = db.GymClasses.Find(id);
            if (gymClass == null)
            {
                return HttpNotFound();
            }
            return View(gymClass);
        }

        // POST: GymClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin2")]
        public ActionResult Edit([Bind(Include = "Id,Name,Description")] GymClass gymClass)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gymClass).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gymClass);
        }

        // GET: GymClasses/Delete/5
        [Authorize(Roles = "Admin2")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GymClass gymClass = db.GymClasses.Find(id);
            if (gymClass == null)
            {
                return HttpNotFound();
            }
            return View(gymClass);
        }

        // POST: GymClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin2")]
        public ActionResult DeleteConfirmed(int id)
        {
            GymClass gymClass = db.GymClasses.Find(id);
            db.GymClasses.Remove(gymClass);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GymBooker1/Controllers/HomeController.cs
using GymBooker1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GymBooker1.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            ViewBag.GymClasses = db.GymClasses.ToList();
            
            ViewBag.cardioDesc = CategoryDescs.GetCategoryDescs()[0];
            ViewBag.toneDesc = CategoryDescs.GetCategoryDescs()[1];
            ViewBag.mindBodyDesc = CategoryDescs.GetCategoryDescs()[2]; 
            ViewBag.strengthDesc = CategoryDescs.GetCategoryDescs()[3];

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

GymBooker1/Views/Home/About.cshtml
<h2>GYMTIME</h2>
<h3>Demo website to show and manipulate a gym timetable</h3>

<p></p>

GymBooker1/Views/Home/Contact.cshtml
<h2>GYMTIME</h2>
<h3>Demo website to show and manipulate a gym timetable</h3>

<address>
    One Made Up Way<br />
    Made Up Town<br />
    Made Up Ville<br />
    Cornwall, UK<br />
    <abbr title="Phone">P:</abbr>
    0111 1111111
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:>richb999@tiscali.co.uk">richb999@tiscali.co.uk</a><br />
</address>

GymBooker1/Views/Home/Index.cshtml
@* Home page (for gym classes)  *@
@* Controller: HomeController  *@


@section containerFluid
{

    <div class="no-margin-home">
        <div class="visible-xs">
            <img src="https://res.cloudinary.com/cloudstoragerb/image/upload/v1577140213/GymBooker/BodyTone2.jpg" class="width100" alt="Home pic" />
        </div>
        <video class="fullwidth hidden-xs" autoplay loop muted>
            <source src="https://res.cloudinary.com/cloudstoragerb/video/upload/v1577141242/GymBooker/b.mp4" type="video/mp4" />
        </video>
        <br /><br />
        <h1 class="text-center">CLASS CATEGORIES</h1>
        <br />
        <div class="container">
            We have a wide range of classes to achieve your goals, whether you want to tone, lose weight, or improve
            endurance or strength, all in a friendly environment and with instructors to give your motivation a
            helping hand. All classes are included in your membership. You can see our full list of classes here.
            To make finding the right classes we have grouped our classes into the categories below:
        </div>
        <br /><br />

        @*//////////////////// LARGER SCREENS //////////////////////////////////////////////////////////////////////////////*@

        @* CARDIO - for side by side boxes, i.e. bigger than small screen*@
        <div class="flex-container hidden-xs hidden-sm">

            <div class="box">

                <div class="">
                    <img src="https://res.cloudinary.com/cloudstoragerb/image/upload/v1577141003/GymBooker/Spin2.jpg" class="width100" alt="Cardio pic" />
                </div>

            </div>

            <div class="box box-centre">
                <div class="width50Centre">
                    <h1>CARDIO</h1>
                    <p class="">
                        @ViewBag.cardioDesc
                    </p>
                    @*@Html.ActionLink("See All", "Index", "GymCategories", new { category = "Cardio" }, new { @class = "btn btn-primary mb-6 rounded", onClick = "buttonClick()" })*@
                    @Html.ActionLink("See All", "Categories", "GymClasses", new { id = "Cardio" }, new { @class = "btn-lg btn-primary mb-6 rounded", onClick = "buttonClick()" })
                </div>
            </div>

        </div>


        @* SCULPT & TONE - for side by side boxes, i.e. bigger than small screen*@
        <div class="flex-container hidden-xs hidden-sm">

            <div class="box box-centre">
                <div class="width50Centre">
                    <h1>SCULPT & TONE</h1>
                    <p class="">
                        @ViewBag.toneDesc
                    </p>
                    @Html.ActionLink("See All", "Categories", "GymClasses", new { id = "Tone" }, new { @class = "btn-lg btn-primary mb-6 rounded", onClick = "buttonClick()" })
                </div>
            </div>

            <div class="box">
                <div class="">
                    <img src="https://res.cloudinary.com/cloudstoragerb/image/upload/v1577140993/GymBooker/Dumbells1.jpg" class="width100" alt="Sculpt and tone pic" />
                </div>
            </div>

        </div>


        @* MIND & BODY - for side by side boxes, i.e. bigger than small screen*@
        <div class="flex-container hidden-xs hidden-sm">

            <div class="box">

                <div class="">
                    <img src="https://res.cloudinary.com/cloudstoragerb/image/upload/v1577140993/GymBooker/Pilates2.jpg" class="width100" alt="Mind & Body pic" />
                </div>

            </div>

            <div class="box box-centre">
                <div class="width50Centre">
                    <h1>MIND & BODY</h1>
                    <p class="">
                        @ViewBag.mindBodyDesc
                    </p>
                    @Html.ActionLink("See All", "Categories", "GymClasses", new { id = "Mind" }, new { @class = "btn-lg btn-primary mb-6 rounded", onClick = "buttonClick()" })
                </div>
            </div>

        </div>


        @* STRENGTH - for side by side boxes, i.e. bigger than small screen*@
        <div class="flex-container hidden-xs hidden-sm bg-warning">

            <div class="box box-centre">
                <div class="width50Centre">
                    <h1>STRENGTH</h1>
                    <p class="">
                        @ViewBag.strengthDesc
                    </p>
                    @Html.ActionLink("See All", "Categories", "GymClasses", new { id = "Strength" }, new { @class = "btn-lg btn-primary mb-6 rounded", onClick = "buttonClick()" })
                </div>
            </div>

            <div class="box">

                <div class="">
                    <img src="https://res.cloudinary.com/cloudstoragerb/image/upload/v1577141004/GymBooker/Strength4.jpg" class="width100" alt="Strength pic" />
                </div>

            </div>

        </div>


        @*//////////////////// SMALLER SCREENS //////////////////////////////////////////////////////////////////////////////*@

        @* CARDIO - for top down boxes, pic first, i.e for small or xs screen*@
        <div class=" visible-xs visible-sm dodgerBlueBackground">

            <div class="">
                <div class="">
                    <img src="https://res.cloudinary.com/cloudstoragerb/image/upload/v1577141003/GymBooker/Spin2.jpg" class="width100" alt="Cardio pic" />
                </div>
            </div>


            <div class="width75Centre text-center smallScreenHeight230">
                <h1>CARDIO</h1>
                <p class="">
                    @ViewBag.cardioDesc
                </p>
                @Html.ActionLink("See All", "Categories", "GymClasses", new { id = "Cardio" }, new { @class = "btn-lg btn-primary mb-6 rounded", onClick = "buttonClick()" })
            </div>


        </div>


        @* SCULPT & TONE - for top down boxes, pic first, i.e for small or xs screen*@
        <div class="visible-xs visible-sm dodgerBlueBackground">

            <div class="">
                <div class="">
                    <img src="https://res.cloudinary.com/cloudstoragerb/image/upload/v1577140993/GymBooker/Dumbells1.jpg" class="width100" alt="Sculpt and tone pic" />
                </div>
            </div>


            <div class="width75Centre text-center smallScreenHeight230">
                <h1>SCULPT & TONE</h1>
                <p class="">
                    @ViewBag.toneDesc
                </p>
                @Html.ActionLink("See All", "Categories", "GymClasses", new { id = "Tone" }, new { @class = "btn-lg btn-primary mb-6 rounded", onClick = "buttonClick()" })
            </div>

        </div>

        @* MIND & BODY - for top down boxes, pic first, i.e for small or xs screen*@
        <div class=" visible-xs visible-sm dodgerBlueBackground">

            <div class="">
                <div class="">
                    <img src="https://res.cloudinary.com/cloudstoragerb/image/upload/v1577140993/GymBooker/Pilates2.jpg" class="width100" alt="Mind & Body pic" />
                </div>
            </div>

            <div class="width75Centre text-center smallScreenHeight230">
                <h1>MIND & BODY</h1>
                <p class="">
                    @ViewBag.mindBodyDesc
                </p>
                @Html.ActionLink("See All", "Categories", "GymClasses", new { id = "Mind" }, new { @class = "btn-lg btn-primary mb-6 rounded", onClick = "buttonClick()" })
            </div>

        </div>

        @* STRENGTH - for top down boxes, pic first, i.e for small or xs screen*@
        <div class=" visible-xs visible-sm dodgerBlueBackground">

            <div class="">
                <div class="">
                    <img src="https://res.cloudinary.com/cloudstoragerb/image/upload/v1577141004/GymBooker/Strength4.jpg" class="width100" alt="Strength pic" />
                </div>
            </div>

            <div class="width75Centre text-center mb-50 smallScreenHeight230">
                <h1>STRENGTH</h1>
                <p class="">
                    @ViewBag.strengthDesc
                </p>
                @Html.ActionLink("See All", "Categories", "GymClasses", new { id = "Strength" }, new { @class = "btn-lg btn-primary mb-6 rounded", onClick = "buttonClick()" })
            </div>

        </div>


    </div>

}